#!/usr/bin/env python3
"""Collapse per-run collection scratch into one run-independent backlog.

Discovery is scoped per run: `DISCOVERY#{run}#{match}` and `RUNPLAYER#{run}#
{puuid}` are rewritten from scratch every time, so each run re-walks the whole
ladder and re-lists every history. The match IDs that fall out overlap almost
completely with the previous run's, which is where the duplication accumulates.

This rewrites that scratch into a single seed run holding one row per match ID
that is still owed a Riot request. Nothing collected is touched: `MATCH#` is the
global dedupe index, the curated objects in S3 are the data, and both are left
exactly as they are. Reports without writing unless --apply is passed.

    python scripts/dedupe_state.py                      # report
    python scripts/dedupe_state.py --apply              # rewrite, prints seed run
    python -m proleague.pipeline --mode full --run-id <seed>

The seeded run is a new run that starts already knowing the backlog, not a
resume: it re-reads the ladder, and `settled()` keeps it from re-fetching
anything already committed.
"""
from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from proleague.config import Config  # noqa: E402
from proleague.curated import settled_scope, settled_status  # noqa: E402
from proleague.pipeline import runtime  # noqa: E402
from proleague.pipeline_state import OwnershipError  # noqa: E402

# Scratch that only ever describes one run. Ladder membership and history
# cursors are re-derived on the next run, and RUNMATCH totals survive on the
# RUN record's new_games plus the run_id stamped into every MATCH record.
SCRATCH = ("RUNPLAYER#", "RUNMATCH#", "LADDER#")


def plan(state, patches, seed_run_id):
    """Decide the rewrite without mutating anything.

    A discovered match is dropped when `MATCH#` already answers for it, so the
    backlog narrows to exactly the games a later run still has to fetch.
    """
    scope = settled_scope(patches)
    known = {r["match_id"]: r for r in state.scan("MATCH#")}
    discovery = state.scan("DISCOVERY#")

    backlog, seen = {}, set()
    for record in discovery:
        mid = record["match_id"]
        seen.add(mid)
        if settled_status(known.get(mid), scope) or mid in backlog:
            continue
        # `puuid` is absent on rows written before discovery attribution; a
        # seeded row keeps whatever the source row carried, so a run that
        # drains the backlog can still advance its history watermarks.
        candidate = {"match_id": mid, "status": "pending"}
        if record.get("puuid"):
            candidate["puuid"] = record["puuid"]
        backlog[mid] = candidate

    # Re-running against an already seeded table is a no-op: rows that are still
    # owed keep their key, and ones that have since settled join the deletions.
    keep = {f"DISCOVERY#{seed_run_id}#{mid}" for mid in backlog}
    stale = [r["pk"] for r in discovery if r["pk"] not in keep]
    for prefix in SCRATCH:
        stale.extend(r["pk"] for r in state.scan(prefix))
    return {
        "seed_run_id": seed_run_id,
        "known_matches": len(known),
        "discovery_rows": len(discovery),
        "discovery_distinct": len(seen),
        "discovery_duplicate_rows": len(discovery) - len(seen),
        "already_settled": len(seen) - len(backlog),
        "backlog_rows": len(backlog),
        "unattributed_backlog": sum("puuid" not in c for c in backlog.values()),
        "rows_deleted": len(stale),
        # Run, request and pointer records are out of scope and stay untouched.
        "rows_after_in_scope": len(known) + len(backlog),
    }, backlog, stale


def apply(state, seed_run_id, backlog, stale):
    """Write the backlog before removing the rows it was derived from.

    Ordering matters: an interruption between the two leaves duplicate scratch,
    which this tool is safe to re-run against, rather than a lost backlog.
    """
    state.put_many([(f"DISCOVERY#{seed_run_id}#{mid}", c) for mid, c in sorted(backlog.items())])
    state.delete_many(stale)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true", help="write the rewrite; otherwise report only")
    parser.add_argument("--seed-run-id", type=lambda v: str(uuid.UUID(v)),
                        help="run ID to hold the backlog; a fresh one is generated by default")
    parser.add_argument("--local", action="store_true")
    args = parser.parse_args(argv)

    cfg = Config.load()
    state, _, _, _ = runtime(cfg, args.local)
    seed = args.seed_run_id or str(uuid.uuid4())
    if not args.apply:
        print(json.dumps({"applied": False, **plan(state, cfg.patches, seed)[0]}, indent=2))
        return 0

    # Take the same exclusive lease a collection does, so the table cannot shift
    # between the scan that decides the rewrite and the writes that perform it.
    lease = str(uuid.uuid4())
    try:
        state.claim(lease)
    except OwnershipError:
        print(json.dumps({"error": "A collection owns ACTIVE; stop it before rewriting its scratch"}))
        return 2
    try:
        report, backlog, stale = plan(state, cfg.patches, seed)
        apply(state, seed, backlog, stale)
    finally:
        state.release(lease)
    print(json.dumps({"applied": True, **report}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
